name = "CD&D"
author = "TheSkyDude"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56c7a59b24302dfbb30ac387fcd3ad4643e587db45f4f2a84049c52708e6cb4e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
