name = "CD&D"
author = "TheSkyDude"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fbd1e322e64572054e73b4b87c804eff6e043d6e8dff8043d2ef54f495ae9ae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
