#Create Aeronautics Toolgun Client Settings
#Sun Sep 13 10:38:06 EDT 2026
autoWeldEnabled=false
bearingAxisMode=AUTO
bearingAxisVisualsEnabled=true
connectedSublevelProximity=2.0
connectionMode=FIXED
deleteRange=8
hudEnabled=true
magneticMarkersEnabled=true
nearbyQueryRange=0
offsetX=0
offsetY=0
offsetZ=0
panel=BLUEPRINTS
previewEnabled=true
rangeDeleteEnabled=false
rotationDegrees=60
rotationStep=15
scalePercent=100
selectedFile=native\:car-base.excraft
snapMode=LEGACY
translateStep=0.25
weldAdjustStep=0.25
weldSelectionMode=FACE_POINTS
